### ISSUE TITLE
Saves

### ISSUE THREAD

**Issue by Rogal80** [AlUlkesh/sd_save_intermediate_images#1]
Hi, great extension :)

Is there any chance to not save image with denoise at N00 just what is set by user?

Right now I am setting N30 but it savings 3 image one with N00 , N30 , and final

**Comment by AlUlkesh** [comment]
You mean, just skip the 00-step? So, if I set it to N10 with 40 steps, just to save N10, N20, N30 (plus the final as normally)?

**Comment by Rogal80** [comment]
Yep, that's correct

**Comment by Rogal80** [comment]
any chance to have a check box for skipping the final image ?

**Comment by AlUlkesh** [comment]
I just comitted the skip-the-000-step.

I'm afraid I don't think I can skip the final (normal) image save from my extension. That would probably require a change in processing.py. But I'll think about it some more.

**Comment by Rogal80** [comment]
Big THX :)
