### ISSUE TITLE
Save to subdir in original output folder

### ISSUE THREAD

**Issue by fmeres** [AlUlkesh/sd_save_intermediate_images#10]
Hello, is there a way to edit the script to have the intermediate directory created inside the output folders that are automatically created in webui (where the original results are saved)? i.e:
outputs/txt2img-images/PROMPT/intermediate_directory

**Comment by AlUlkesh** [comment]
Can you put your ui-config.json and config.json here? I think this depends on some settings you have set, which I might not have thought about.

**Comment by AlUlkesh** [comment]
Nevermind. I think I know what it is. You are probably using this setting?

![image](https://user-images.githubusercontent.com/99896447/212192383-03907cea-995a-41a0-9757-eea4ca9ef4f2.png)

If so, I just changed the code, so the latest commit will support this.

**Comment by fmeres** [comment]
That's exactly right. Thank you for implementing it!
