### ISSUE TITLE
[Feature Request] Auto Steps Generation

### ISSUE THREAD

**Issue by totalschaden** [AlUlkesh/sd_save_intermediate_images#13]
Would it be possible to add an option to Generate Images of specific seed with a selectable Step range, and generate every x Steps to make a gif ?

Also have optional intermediate images on/off to save in a folder with all steps too.

Something like this:
https://i.imgur.com/OWno74z.gif

**Comment by AlUlkesh** [comment]
I'm afraid I don't quite get what you mean. Your example looks like different prompts / a changing prompt? Can you elaborate please?

**Comment by totalschaden** [comment]
Its all the same Prompt and Seed, just different Steps.

I made this today its Step 2-90, in total it includes 8 seeds (8x 2-90)

https://imgur.com/1h19K2p

**Comment by AlUlkesh** [comment]
Let's see if I'm understanding correctly. For example:

- seed to use: 1, 20, 300
- steps per seed: 90
- starting at step: 5
- generate every x steps: 3
- and once everything is done, make a single gif out of it

?

**Comment by totalschaden** [comment]
Yep, where seed to use could be 1 number then increase by batch (if used) or batch 8 and 8 seeds given, use given seeds

Once done optional, make gif per Img or Single Gif of all.

Save all Images in Seperated Folder

**Comment by AlUlkesh** [comment]
I thought about this, but I think I'd pretty much would have to rewrite from the ground up to accomplish it. It would have to work more like the x/y-Script. Currently it hooks into the processing, while this would have to be further "out".

However, I have implemented a "Start at image". So you could combine this extension with x/y and set the seed there.
