### ISSUE TITLE
Save the images shown in livePreview

### ISSUE THREAD

**Issue by wojteksosnowski** [AlUlkesh/sd_save_intermediate_images#14]
Images saved by the extension are different than those visible in livePreview. Save those instead.

**Comment by AlUlkesh** [comment]
That shouldn't be the case. Do you haven an example?

**Comment by wojteksosnowski** [comment]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/46383030/212862687-c6ff530b-9da4-4bd5-baef-8b8a47badfe6.png">
Just as it is in the settings menu. It is very useful in workflows that include inpainting with a mask. These settings give you good interpolation between generated image and masked content.

**Comment by AlUlkesh** [comment]
Yes, that is exactly how it works for me.

Can you check the "debug" checkbox and post the console log?
And perhaps a screenshot of how the preview looks different from the intermediate files?

**Comment by wojteksosnowski** [comment]
input:
![cropdom-kredytowy-2x-kopia](https://user-images.githubusercontent.com/46383030/212874711-7f2bd927-b093-44de-8a33-e041d6d3902d.png)

mask:
![00059-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874881-ec1db12a-ae04-43b6-be89-8a59c4369fb1.png)

from extension:

![01354-010-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874357-c246712e-6915-41a6-8170-3ef994efe189.png)
![01354-008-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874365-a5d283b8-849c-417b-b992-1f101cda26ad.png)
![01354-006-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874367-6a15ae6a-bf1f-4a9f-90f0-79f0e482e755.png)
![01354-004-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874375-8b95ef2e-d3a5-43e3-8a0a-5f08e57f6862.png)
![01354-002-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874377-7e8e619e-32fd-4900-bca1-6196bc065dca.png)

captured from livePreview

![download-24](https://user-images.githubusercontent.com/46383030/212874476-b739f8f2-05bd-4b63-a734-1a876d3ff8ad.png)
![download-23](https://user-images.githubusercontent.com/46383030/212874483-eecab44f-84cf-48ac-b054-bbd2da113376.png)
![download-22](https://user-images.githubusercontent.com/46383030/212874487-08dc0579-05ca-4792-addc-7706124158cf.png)
![download-21](https://user-images.githubusercontent.com/46383030/212874489-960c0134-178a-4606-a421-675cd5e0820f.png)
![download-20](https://user-images.githubusercontent.com/46383030/212874491-dfa4cc44-e379-4f40-ae0f-e9efa8b9a822.png)

final:
![01354-3972346835-analog style illustration warhammer 40k chaos space marine character, standing on a burning battlefield in the background, crumb](https://user-images.githubusercontent.com/46383030/212874630-7f1ce55e-2468-4f94-823d-f7c5a55ec254.png)

settings:
![Przechwytywanie zawartości sieci Web_17-1-2023_112756_127 0 0 1](https://user-images.githubusercontent.com/46383030/212875087-eb63276f-9788-41c8-8fe8-718a72f8d199.jpeg)

debug:
![Snipaste_2023-01-17_11-29-09](https://user-images.githubusercontent.com/46383030/212875332-e2f01ca5-5280-47ae-8c50-551e03642195.jpg)

**Comment by AlUlkesh** [comment]
Thanks, I can reproduce it now. I'll look into it.

**Comment by wojteksosnowski** [comment]
That would be awesome. This effect is great for compositing.

**Comment by AlUlkesh** [comment]
Turns out that function was just implemented 3 days ago:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f94a215abed85b34ae978853078812801d3e7738

I put in a new option, that should do the trick:
![image](https://user-images.githubusercontent.com/99896447/212945687-8ebf8462-853b-49f7-9b6e-97b323b4e5b0.png)
This now takes the intermediate saves directly from the preview image.
While implementing this I ran into aproblem: Since only one image is displayed in the preview, I would end up with repeats of the same image with batch_size > 1. For now I'm falling back to simple "denoised" for images after batch_size > 1.

Let me know, if this does, what you expected.

**Comment by wojteksosnowski** [comment]
Hey, extension saves the right images from live preview. But if you change n skip to anything else than 5 it crashes.

**Comment by wojteksosnowski** [comment]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/46383030/213012820-6f68b1bd-09bd-46cf-ac52-94d3c99f0bf1.png">

![Przechwytywanie zawartości sieci Web_17-1-2023_22834_127 0 0 1](https://user-images.githubusercontent.com/46383030/213012843-e2c211e5-ee8c-44d5-b5cf-5767668b4ce5.jpeg)

**Comment by AlUlkesh** [comment]
Works for me, with, I think, the same settings. I hate bugs like that...

I'll need the full console log with debug for that, beginning with starting the webui-user, until the error.
```
venv "automatic\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct  7 2022, 20:14:50) [MSC v.1916 64 bit (AMD64)]
Commit hash: e0e80050091ea7f58ae17c69f31d1b5de5e0ae20
...
```

**Comment by wojteksosnowski** [comment]
Well, I am having trouble with recreating it. So maybe it was just a fluke. Is it possible to add an option to save only last N previews?
