### ISSUE TITLE
Request - put the incremental numbers at the end of the name string

### ISSUE THREAD

**Issue by ReinerBforartists** [AlUlkesh/sd_save_intermediate_images#24]
Hey,

Currently the name pattern puts the incremental numbers for the single images in front of the name. When i import this sequence into let's say DaVinci resolve, then i cannot import it as an image sequence. But each little image gets treaten independently. Means i would need to fix 150 images to have a duration of one frame again instead of 5 seconds.

Could the output be written with a name pattern where the values are at the end of the string? That's the common pattern for image sequences. At the moment it is xxx0001xxxxxxxxxxxxxxxx.png. Needed would be xxxxxxxxxxxxxxxxxxxxxx0001.png

Many thanks for reading and considering.

Kind regards
Reiner

**Comment by AlUlkesh** [comment]
I put this option in for you:

![image](https://user-images.githubusercontent.com/99896447/224535850-daffa94b-eddf-4871-9329-0e98cef3eb08.png)

Let me know if this works for you.

**Comment by ReinerBforartists** [comment]
Works like charm. Many thanks :)
