### ISSUE TITLE
AttributeError: intermed_hires_start

### ISSUE THREAD

**Issue by ReinerBforartists** [AlUlkesh/sd_save_intermediate_images#25]
Hi,

I experience an attribute error with using a batch count higher than one. Error log output can be found below the image

Kind regards
Reiner

![error1](https://user-images.githubusercontent.com/13919702/224538997-edba9ea4-8ab9-48a2-8828-9d15fca139fe.jpg)

[errorlog.txt](https://github.com/AlUlkesh/sd_save_intermediate_images/files/10950576/errorlog.txt)

**Comment by AlUlkesh** [comment]
Thanks for including the debug info right away.

Should be fixed with this commit.

**Comment by ReinerBforartists** [comment]
Confirming that it works. Good job :)
