### ISSUE TITLE
what "Smoothing / Interpolate" does to the output??

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/sd_save_intermediate_images#26]
there are no docs and explanation about it.

**Comment by AlUlkesh** [comment]
You can see the difference on the main page / readme.
There are examples without and with interpolating.

For the concept itself: https://en.wikipedia.org/wiki/Motion_interpolation

**Comment by LanceGao97** [comment]
This is fucking true ,man,
im a former video editor and learning game character design.
   I play SD for a month , and the most exicting thing is I really love to see the preview morphs 
to final.    however,  the default auto1111  live preview  (Full option) tooks  far more GPU RAM  than I expected,  
DefaultAuto1111  Live Preview--Full option---> too high GPU RAM occupation
if im creating a 800:1200 image,  no hires fix,    4070Ti12G,
Live Preview -- Full                                                 about   11   GPU RAM all time until the end       
                    -- Approx NN      1/2 resolution           about   5G   GPU RAM      
                   --- APProx Cheap 1/4 resolution           about  5G   GPU RAM
for some reason,  if you turn this to Full,  the GPU RAM seems have a hard time doing something, 
let alone turn on HighRex Fix,
with HighRes Fix, itwill crash  immdietaly after  maybe just 5 steps . 
---------------

**Comment by AlUlkesh** [comment]
I was running a 2060 with 6GB for the longest time. Are you using xformers?
