### ISSUE TITLE
UI issue, empty bottom space, and no round corner.

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/sd_save_intermediate_images#29]
screenshots
https://postimg.cc/Z0JdFvrx

https://postimg.cc/8swryk4Q

could you please fix this?

**Comment by AlUlkesh** [comment]
That was actually a special request, to avoid "Script" from running into the extension's UI:
![image](https://user-images.githubusercontent.com/99896447/226163619-07890202-8798-47e3-8deb-19988fdb0134.png)

See https://github.com/AlUlkesh/sd_save_intermediate_images/issues/9

**Comment by bryanray** [comment]
i see, but the round corner can be done? right? it will be amazing to look flush to the rest of the UI :))

thanks for this cool plugin

**Comment by bryanray** [comment]
fun thing is, all of them in the accordion menu, lost the round corner in the bottom line :)

**Comment by bryanray** [comment]
> Ah, ok. I've removed the padding.
> 
> Yeah, the Gradio update is giving me major headaches in some of my other extensions...

you dont say, every other app has gone wonky, even the webui itself has some minor UI issue but they dont address it hard enough, looks like no one cares much about UI
