### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by LanceGao97** [AlUlkesh/sd_save_intermediate_images#32]
Hi,
 I love your script, it works .

sorry， wrong way of testing,  It works perfectly today . video and inter images all good.
maybe the way I did has something wrong. 

no suggestion anymore,  it works nicely.

------------------------ you can close this issue.

------------------  -----------GPU RAM occupation
Full ---------------------11G  
APPROX  NN-----------  5G
APPROX cheap---------- 5G

so my suggestion is :

 1. save image only from Approx NN  ,
 2. every image saved resolution = Final size,   (if Hires On,  FinalSize= Hires size,  if HiresOff ,  FinalSize= base size).   
     
probably This can also help FFmpeg creating low res and hi res together in a single video.  
currently , this script can't combine lowres and hires images into a single video, maybe because of not same resolution size, i don't know.

**Comment by LanceGao97** [comment]
Here is a image I created on Civitai
I used the preview image, about nearly 80% to the final,  I don't like the final image cause  the colorful pixels and warm feelings  are lost,    what I used is a screen shot . and put that blured img to img2img.  after some tweaking, the final image , you can see all those warm feeling pixels from the screen shot became those colorful decorations .

https://civitai.com/images/497441?period=AllTime&periodMode=published&sort=Newest&view=categories&username=lanceg&withTags=true
https://civitai.com/images/429548?period=AllTime&periodMode=published&sort=Newest&view=categories&username=lanceg&withTags=true


![Snapshot 3](https://user-images.githubusercontent.com/125782753/235421373-7ed507b6-9a27-4fec-af78-329bc571fac0.png)

**Comment by AlUlkesh** [comment]
As in the other issue, I wonder if you are using xformers, it was enough to get by with 6GB for me.

You can create a single video with lores and hires, by checking both boxes:
![image](https://user-images.githubusercontent.com/99896447/235449813-bfa5606d-2609-495d-a13e-195580a119e5.png)

**Comment by LanceGao97** [comment]
Well,  I just tested it again,  It works perfectly,  intermediate and the video all good,  under both Live preview set to FULL or APProx
 
Thats not what happend last night,  maybe  because last night im testing it with another extension called Save AnimationSteps, 
maybe that are conflict.    Sorry for this issue and my suggestion are bad, don't think about it,  this is good .I want delete my words.

**Comment by AlUlkesh** [comment]
All good, don't worry 😄
