### ISSUE TITLE
doesn't seem to generate a video...

### ISSUE THREAD

**Issue by XeonG** [AlUlkesh/sd_save_intermediate_images#37]
Calculating sha256 for C:\Projects\StableDiffusion\stable-diffusion-webui\models\VAE\sdxl_vae.safetensors: 235745af8d86bf4a4c1b5b4f529868b37019a10f7c0b2e79ad0abca3a22bc6e1
100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:09<00:00,  4.39it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:09<00:00,  4.46it/s]
Total progress: 166it [03:36,  1.30s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:16<00:00,  2.45it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:16<00:00,  2.48it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 82/82 [00:35<00:00,  2.29it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:17<00:00,  2.36it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:16<00:00,  2.45it/s]
*** Error running postprocess: C:\Projects\StableDiffusion\stable-diffusion-webui\extensions\sd_save_intermediate_images\scripts\sd_save_intermediate_images.py
    Traceback (most recent call last):
      File "C:\Projects\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Projects\StableDiffusion\stable-diffusion-webui\extensions\sd_save_intermediate_images\scripts\sd_save_intermediate_images.py", line 731, in postprocess
        make_video(p, ssii_is_active, ssii_final_save, ssii_intermediate_type, ssii_every_n, ssii_start_at_n, ssii_stop_at_n, ssii_mode, ssii_video_format, ssii_mp4_parms, ssii_video_fps, ssii_add_first_frames, ssii_add_last_frames, ssii_smooth, ssii_seconds, ssii_lores, ssii_hires, ssii_ffmpeg_bat, ssii_bat_only, ssii_debug)
      File "C:\Projects\StableDiffusion\stable-diffusion-webui\extensions\sd_save_intermediate_images\scripts\sd_save_intermediate_images.py", line 177, in make_video
        make_video_or_bat(p, ssii_is_active, ssii_final_save, ssii_intermediate_type, ssii_every_n, ssii_start_at_n, ssii_stop_at_n, ssii_mode, ssii_video_format, ssii_mp4_parms, ssii_video_fps, ssii_add_first_frames, ssii_add_last_frames, ssii_smooth, ssii_seconds, ssii_lores, ssii_hires, ssii_ffmpeg_bat, ssii_bat_only, ssii_debug)
      File "C:\Projects\StableDiffusion\stable-diffusion-webui\extensions\sd_save_intermediate_images\scripts\sd_save_intermediate_images.py", line 254, in make_video_or_bat
        os.replace(path_name_org, path_name_seq)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'outputs/txt2img-images\\sd_xl_base_1.0\\intermediates\\00000\\00000-041-1818421718.png' -> 'outputs/txt2img-images\\sd_xl_base_1.0\\intermediates\\00000\\00000-1061-1818421718.png'

---

**Comment by AlUlkesh** [comment]
I just tried it on my end, it works here, so it's at least not a general problem.

Can you check the debug box and post the output?

**Comment by XeonG** [comment]
ahh in debug it mentioned ffmpeg missing... new system build forgot to add ffmpeg to the system path.. it works now.

might want to add some check for ffmpeg, wouldn't have realized that without debug output being on

**Comment by AlUlkesh** [comment]
Ah, good.

Yes, I should put that in, makes sense.
