### ISSUE TITLE
[Feature request]After N steps -skip 

### ISSUE THREAD

**Issue by Rogal80** [AlUlkesh/sd_save_intermediate_images#4]
Hi, maybe there is a possibility to add a checkbox that will skip after N steps and save the image?

**Comment by AlUlkesh** [comment]
I'm not sure I understand exactly. Can you give me an example?

**Comment by Rogal80** [comment]
For example, if I will set checkbox with skip and N steps for 30 after 30 steps it will behave like skip button but also save image with 30 steps

**Comment by AlUlkesh** [comment]
How is this different from not using the extension and generating an image with only 30 steps?

**Comment by Rogal80** [comment]
Like I showed you in my request https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/983 with Higres.fix the second pass adding a lot of noise in the last 25- 30 % of steps - having this option for me will reduce noise/detail and allow to save a lot of time when I will run batch of image

**Comment by AlUlkesh** [comment]
Ah, yes, the highres issue.

I tried a few things and I think I now found out how to do it, just from the extension. I'll get to it.

**Comment by AlUlkesh** [comment]
I just committed the change. In your case, if you have for example 40 steps and want to only see step 30, you can input it like this:

![image](https://user-images.githubusercontent.com/99896447/209423055-cf088d97-9638-48e4-a967-6b3e44ab89fb.png)

This would save step 30 before hires as an intermediate and step 30 with hires as the final file. Processing is then immediately stopped.

Let me know, if this does what you need.

**Comment by Rogal80** [comment]
Hi, it works perfectly :) THX you are great :)
