### ISSUE TITLE
'=' alignment error

### ISSUE THREAD

**Issue by vincnt0** [AlUlkesh/sd_save_intermediate_images#5]
Got this error:

`in callback_state
    intermed_number = f"{intermed_number:0{digits}}"
ValueError: '=' alignment not allowed in string format specifier`

fixed it by removing the "0" in the format string in lines 149 and 153 :)

**Comment by AlUlkesh** [comment]
Thanks. Though I don't see yet, what the problem might be, the 0 should pad the number with leading zeroes.

Can you show me the final filename and one of the intermediates?

**Comment by vincnt0** [comment]
Sure, here's some sample filenames:
intermediates in folder "00536": 
"00536-005-2861772760-road` in a peppermint forest, fantasy, digital art.png",
"00536-010-2861772760-road in a peppermint forest, fantasy, digital art.png",
etc.
(counts correctly in steps of 5)

final image:
"00536-2861772760-road in a peppermint forest, fantasy, digital art.png"

I'm also not exactly sure what is going on (any why it works for you and not for me), but according to this [stackoverflow post](https://stackoverflow.com/questions/36044676/text-formatting-error-alignment-not-allowed-in-string-format-specifier?rq=1), this "= alignment" implies that the function should expect numerical input instead of a string input:

> So by specifying 0N as the “zero-padding to N width”, you have implied both “the input is a numeric type”, and “the zeros should go between the sign and the digits”. That latter implication is what is meant by '=' alignment.  
Since the value "1" is not numeric, the “=”-alignment handling code raises that exception. The message is written expecting you know what it's talking about because you requested (by implication) the “=” alignment.

**Comment by AlUlkesh** [comment]
I just ran it through the debugger, but even when I put letters in the variable, I don't get any error.

Which version of python are you running?

**Comment by haraldini** [comment]
Getting the same issue.
Python 3.9.12

**Comment by AlUlkesh** [comment]
Thanks, it was the python version. Apparently they have improved on that in 3.10.

I now coded it slightly different, which works on both versions.
