### ISSUE TITLE
Margin bottom

### ISSUE THREAD

**Issue by CJohnDesign** [AlUlkesh/sd_save_intermediate_images#9]
Feature request: margin-bottom

Add the standard padding bottom to the wrapper

<img width="865" alt="image" src="https://user-images.githubusercontent.com/10375280/211711758-0cb1d9da-3b26-42f8-96f5-4a589f2c3e26.png">

**Comment by AlUlkesh** [comment]
Can you show me an extension that has this?

**Comment by AlUlkesh** [comment]
I added a padding row. I think that does the trick.
